<a href="https://colab.research.google.com/github/kartik580/NUMPY-EXTRACT-DATA/blob/main/numpy_EXTRACT_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
marks= (1,2,3,4,5,6,4,5,6,6,2,5,)

In [3]:
student= np.array(marks)
print(marks)

(1, 2, 3, 4, 5, 6, 4, 5, 6, 6, 2, 5)


In [4]:
print(type(marks))

<class 'tuple'>


In [5]:
print(marks)

(1, 2, 3, 4, 5, 6, 4, 5, 6, 6, 2, 5)


In [6]:
student={
    "marks":["a","b","c"],
    "marks":[20,50,40]
}

In [7]:
marks= np.array(student["marks"])
print(marks)

[20 50 40]


In [8]:
np.array([1.0,2.5,3.4,6.4]).dtype

dtype('float64')

In [9]:
np.arange(10,1,-1)

np.arange(1,10)

np.arange(1,101,+3)

np.arange(1,500,50).dtype




dtype('int64')

In [10]:
np.random.randint(1,100)     #one random no create karna hota hai
# it always int values return

38

In [11]:

np.random.randint(1,100,5).dtype

dtype('int64')

In [12]:

np.random.randint(1,100,10).reshape(5,2)

array([[23, 16],
       [89, 49],
       [49, 50],
       [29, 57],
       [88, 51]])

In [13]:
np.random.randint(1,100,20)

array([31, 26,  7, 58, 42, 12, 71, 52, 28, 73, 80, 20,  9, 24, 37, 36, 17,
       61, 13, 89])

In [14]:
np.zeros(5)
np.zeros(20).dtype


dtype('float64')

In [15]:
np.ones(10)
np.ones(1)

array([1.])

In [16]:
np.zeros(55,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.full(52,1)     #repeate value 5 time

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [18]:
np.linspace(1,100,14)   #linspace = linear spacing  ,,divide equal part 1,10 and any given no

array([  1.        ,   8.61538462,  16.23076923,  23.84615385,
        31.46153846,  39.07692308,  46.69230769,  54.30769231,
        61.92307692,  69.53846154,  77.15384615,  84.76923077,
        92.38461538, 100.        ])

In [19]:
np.linspace(1,200).size      # total no of result calculate size

50

In [20]:
np.array([[1,2,3,4],
          [2,3,4,5]]).shape
np.array([[1,2,3,45,6,7,8,9],
          [1,2,3,4,5,6,7,8]])

array([[ 1,  2,  3, 45,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8]])

In [21]:
#1 employee salary
salary = np.array([35000,45000,56000,65000])
print(salary)

[35000 45000 56000 65000]


In [22]:
# 2 netflix watch hours
netflix={
    "watch_hours":[4.5,12.5,18.0,2.3,31.5]
}
watch_hours=np.array(netflix["watch_hours"])
print(watch_hours)

[ 4.5 12.5 18.   2.3 31.5]


In [23]:
plans=np.array([149,199,499])
print(plans)

[149 199 499]


In [24]:
# agent confidence
openAI={
    "confidence":[0.91,0.72,0.88,0.64,523.126]
}
confidence=np.array(openAI["confidence"])
print(confidence)

[  0.91    0.72    0.88    0.64  523.126]


In [25]:
# integer range with arange
years= np.arange(2020,2029)
print(years)

[2020 2021 2022 2023 2024 2025 2026 2027 2028]


In [26]:
num = np.arange(1,100)
print(num)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [27]:
salary_bands= np.arange(30000,100000,10000)
print(salary_bands)

[30000 40000 50000 60000 70000 80000 90000]


In [28]:
# learning_rate grid with linspace
learning_rate= np.linspace(1,100,10)
print(learning_rate)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [29]:
# age grid with linspace
age_grid=np.linspace(18,60,16,dtype=int)
print(age_grid)

[18 20 23 26 29 32 34 37 40 43 46 48 51 54 57 60]


In [30]:
empty_batch= np.zeros((4,6))
print(empty_batch)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [31]:
zeros = np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [32]:
ones = np.ones((5,6))
print(ones)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [33]:
ones = np.ones(5)
print(ones)

[1. 1. 1. 1. 1.]


In [34]:
# matrix with weights
weights = np.full((3,4,6),10)
print(weights)

[[[10 10 10 10 10 10]
  [10 10 10 10 10 10]
  [10 10 10 10 10 10]
  [10 10 10 10 10 10]]

 [[10 10 10 10 10 10]
  [10 10 10 10 10 10]
  [10 10 10 10 10 10]
  [10 10 10 10 10 10]]

 [[10 10 10 10 10 10]
  [10 10 10 10 10 10]
  [10 10 10 10 10 10]
  [10 10 10 10 10 10]]]


In [35]:
weights = np.full((3,4),10)
print(weights)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [36]:
# identity matrix
identity =np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [37]:
# salary bonus constant
bonus =np.full(6,5000)
print(bonus)
bonusin2= np.full((4,4),6000)
print(bonusin2)

[5000 5000 5000 5000 5000 5000]
[[6000 6000 6000 6000]
 [6000 6000 6000 6000]
 [6000 6000 6000 6000]
 [6000 6000 6000 6000]]


In [38]:
salary= np.array([[1,2],[3,5],[5,6]])
print(salary.shape)
salary= np.array([1,2,5,6])
print(salary.shape)
salary = np.array([[1],[2],[5]])
print(salary.shape)

(3, 2)
(4,)
(3, 1)


In [39]:
# num of dimension
print(salary.ndim)

2


In [40]:
num = np.array([[1,2,3],[2,3,4],[4,5,6]])
print(num)

[[1 2 3]
 [2 3 4]
 [4 5 6]]


In [41]:

salary = np.array([20000,30000,40000,4000000,500000])
print(salary)

[  20000   30000   40000 4000000  500000]


In [42]:
import numpy as np

In [43]:
num = np.random.uniform(1,100,6)            # return float type data
print(num)

[30.29266213  4.44259867 25.35988141 45.98571676  4.45022587 69.32986539]


In [44]:
marks =np.random.uniform(1,100,6)
print(marks.dtype)

float64


In [45]:
marks =np.random.uniform(1,100,6)
print(marks.size)

6


In [46]:
marks =np.random.uniform(1,100,6)
print(marks.shape)

(6,)


In [47]:
marks =np.random.uniform(1,100,6)
print(marks.ndim)

1


In [48]:
marks =np.random.uniform(1,100,6)
print(marks.itemsize)

8


In [49]:
marks =np.random.randint(1,100,6)
print(marks.itemsize)

8


In [50]:
marks =np.random.uniform(1,100,20)
print(marks)
len(marks)
marks.resize(5,4)

[69.86530854 38.38119016 79.68316231 51.28530958 14.36719134 83.06967726
 41.8651728  37.11555075 73.82614042 37.7931357  31.27497699 28.1423047
 99.5981123  16.64579069  4.74378454 34.91023138 57.99197864 61.99390474
  1.62786044 50.84567695]


In [51]:
marks =np.random.uniform(1,100,20)
print(marks)
marks= marks.resize(5,4)

[87.23898316 11.91441266 98.14617573 88.81380049 99.81014278 45.54687744
 52.4873354  77.25476164 74.30837129 27.60372607 28.408076   91.19496379
 61.97314375 49.76179097 38.08987134 37.617055   25.10705482 79.50837984
 99.55014775 29.95774005]


In [52]:
img= np.linspace(1,100,20)
print(img)

[  1.           6.21052632  11.42105263  16.63157895  21.84210526
  27.05263158  32.26315789  37.47368421  42.68421053  47.89473684
  53.10526316  58.31578947  63.52631579  68.73684211  73.94736842
  79.15789474  84.36842105  89.57894737  94.78947368 100.        ]


size is a multipliction  and parameter

size is a atribute where is a function


In [53]:
img=img.reshape(2,10)
img.shape

(2, 10)

In [54]:
img.shape

(2, 10)

In [55]:
img=img.reshape(2,5,2)
img.shape

(2, 5, 2)

In [56]:
img =img.reshape(1,2,10)
img.shape

(1, 2, 10)

In [57]:
print(img)

[[[  1.           6.21052632  11.42105263  16.63157895  21.84210526
    27.05263158  32.26315789  37.47368421  42.68421053  47.89473684]
  [ 53.10526316  58.31578947  63.52631579  68.73684211  73.94736842
    79.15789474  84.36842105  89.57894737  94.78947368 100.        ]]]


In [58]:
img =img.reshape(10,2,1)
img.shape

(10, 2, 1)

In [59]:
print(img)

[[[  1.        ]
  [  6.21052632]]

 [[ 11.42105263]
  [ 16.63157895]]

 [[ 21.84210526]
  [ 27.05263158]]

 [[ 32.26315789]
  [ 37.47368421]]

 [[ 42.68421053]
  [ 47.89473684]]

 [[ 53.10526316]
  [ 58.31578947]]

 [[ 63.52631579]
  [ 68.73684211]]

 [[ 73.94736842]
  [ 79.15789474]]

 [[ 84.36842105]
  [ 89.57894737]]

 [[ 94.78947368]
  [100.        ]]]


In [60]:
print(img)

[[[  1.        ]
  [  6.21052632]]

 [[ 11.42105263]
  [ 16.63157895]]

 [[ 21.84210526]
  [ 27.05263158]]

 [[ 32.26315789]
  [ 37.47368421]]

 [[ 42.68421053]
  [ 47.89473684]]

 [[ 53.10526316]
  [ 58.31578947]]

 [[ 63.52631579]
  [ 68.73684211]]

 [[ 73.94736842]
  [ 79.15789474]]

 [[ 84.36842105]
  [ 89.57894737]]

 [[ 94.78947368]
  [100.        ]]]


In [61]:
img= img.reshape(2,2,5)
img.shape
print(img)

[[[  1.           6.21052632  11.42105263  16.63157895  21.84210526]
  [ 27.05263158  32.26315789  37.47368421  42.68421053  47.89473684]]

 [[ 53.10526316  58.31578947  63.52631579  68.73684211  73.94736842]
  [ 79.15789474  84.36842105  89.57894737  94.78947368 100.        ]]]


In [62]:
marks= np.arange(1,100,dtype="int32")
marks.dtype

dtype('int32')

In [63]:
marks= np.arange(1,100,dtype="int16")
marks.dtype

dtype('int16')

In [64]:
marks= np.arange(1,100,dtype="int8")
marks.dtype

dtype('int8')

In [65]:
marks= np.arange(1,100,dtype="int8")


In [66]:
import numpy as np

In [67]:
marks= np.random.randint(1,100,dtype="int32")
marks.dtype

dtype('int32')

In [68]:
marks= np.random.uniform(1,100)
print(marks)


7.497404038763083


In [69]:
import numpy as np
np.array(marks).dtype

dtype('float64')

In [70]:
import numpy as np

In [71]:
marks= np.array([1,3,2,4,5,6])
marks.dtype

dtype('int64')

In [72]:

print(marks)
marks.dtype

[1 3 2 4 5 6]


dtype('int64')

In [73]:
marks.itemsize

8

In [74]:
marks=np.array(marks.astype(float))

In [75]:
marks.dtype

dtype('float64')

In [76]:
m= np.array([1,2,3,4,5,6,7],dtype=np.int16)

In [77]:
m.dtype
m.itemsize

2

In [78]:
m.astype(np.float16)

array([1., 2., 3., 4., 5., 6., 7.], dtype=float16)

In [79]:
m=m.astype(np.float16)

In [80]:
m.dtype

dtype('float16')

In [81]:
arr=np.array([5,6,4,8,9])
arr.dtype

dtype('int64')

In [82]:
arr.astype(np.int32)

array([5, 6, 4, 8, 9], dtype=int32)

In [83]:
arr=np.array([5,6,4,8,9],dtype="int32")

In [84]:
arr.dtype

dtype('int32')

In [85]:
arr=arr.astype(np.float16)

In [86]:
arr.dtype

dtype('float16')

In [87]:
arr=np.array([5,6,4,8,9],dtype="float32")

In [88]:
arr.dtype

dtype('float32')

In [89]:
arr=np.array([5,6,4,8,9],dtype="float64")
arr.dtype

dtype('float64')

In [90]:
print(arr)
arr.dtype

[5. 6. 4. 8. 9.]


dtype('float64')

In [91]:
marks= np.random.randint(1,100,20)
print(marks)

[25  6  8 47 39  8 18 18 79 74 19 84 97  8 12 95 42 55 62 11]


In [92]:
import numpy as np


In [93]:
score=np.array([1,2,3,4,5,6,7,8])
print(score)

[1 2 3 4 5 6 7 8]


In [94]:
score= score.reshape(2,4)
print(score)

[[1 2 3 4]
 [5 6 7 8]]


In [95]:
sct= np.random.randint(1,10000,800)
print(sct.shape)

(800,)


In [96]:
sct= sct.reshape(40,20)
print(sct.shape)


(40, 20)


In [97]:
sct= sct.reshape(25,2,2,4,2)
print(sct.shape)


(25, 2, 2, 4, 2)


In [98]:
sct=np.full(200,56)
print(sct)

[56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56
 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56
 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56
 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56
 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56
 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56
 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56
 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56
 56 56 56 56 56 56 56 56]


In [99]:
data= np.full((65,75),23,dtype="int16")
print(data.size)
print(data.shape)
print(data.ndim)
print(data.itemsize)
print(data.dtype)

4875
(65, 75)
2
2
int16


In [100]:
data.astype(np.float32)
data= data.astype(np.float32)

In [101]:
print(data.dtype)

float32
